### ISSUE TITLE
ENH allow to grow the number of atoms with set_worker_D

### ISSUE THREAD

**Issue by tomMoral** [tomMoral/dicodile#53]
To be consistent with the API in `alphcsc`, `set_worker_D` should allow to have a dictionary with more atoms than the current one. https://github.com/alphacsc/alphacsc/blob/c4474d19b22687425ffe4a724dfe6d542943a318/alphacsc/_z_encoder.py#L375-L385

In this case, z_hat should be updated accordingly.

**Comment by rprimet** [comment]
Do we want that to be implicit or explicit? e.g. either have a "update n_atoms count" command or just assume that, when the workers receive a D whose 0th dimension is greater than the previous one, they should silently pad the representation of Z with additional (zero-filled) rows?

**Comment by tomMoral** [comment]
I would say explicit, so we avoid weird behavior

Le mar. 6 sept. 2022 à 13:52, Romain Primet ***@***.***> a
écrit :
